name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 新機能・機能追加 / New Features'
    semver-increment: patch
    when: 
      labels:
        - 'feature'
        - 'enhancement'
  - title: '🐛 バグ修正 / Bug Fixes'
    when:
      labels:
        - 'bug'
        - 'fix'
  - title: '🧰 依存関係・ビルド調整 / Maintenance'
    when:
      labels:
        - 'dependencies'
        - 'chore'
        - 'ci'
  - type: 'pre-exclude'
    when:
      labels:
        - 'skip-changelog'
  - type: 'version-resolver'
    semver-increment: 'major'
    when: 
      labels:
        - 'release:major'
  - type: 'version-resolver'
    semver-increment: 'minor'
    when: 
      labels:
        - 'release:minor'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## 変更内容 / What's Changed
  $CHANGES