name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
prerelease: true
prerelease-identifier: '-dev, alpha, beta'
categories:
  - title: '🚀 新機能・機能追加 / New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 バグ修正 / Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧰 依存関係・ビルド調整 / Maintenance'
    labels:
      - 'dependencies'
      - 'chore'
      - 'ci'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## 変更内容 / What's Changed
  $CHANGES